name: botika_socket_client
description: Botika Socket Client Flutter Plugin
version: 1.0.0
homepage: https://github.com/botika-online/botika-socket-client-flutter
repository: https://github.com/botika-online/botika-socket-client-flutter
issue_tracker: https://github.com/botika-online/botika-socket-client-flutter/issues

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  socket_io_client: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
